import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tomeks
 */
public class tictactoe extends javax.swing.JFrame {
    char p1,p2,p3,p4,p5,p6,p7,p8,p9, kto;

    /**
     * Creates new form tictactoe
     */
    public tictactoe() {
        initComponents();
        p1='n';
        p2='n';
        p3='n';
        p4='n';
        p5='n';
        p6='n';
        p7='n';
        p8='n';
        p9='n';
        kto='o';
    }
    private void Resetuj(){
        pole1.setIcon(null);
        pole2.setIcon(null);
        pole3.setIcon(null);
        pole4.setIcon(null);
        pole5.setIcon(null);
        pole6.setIcon(null);
        pole7.setIcon(null);
        pole8.setIcon(null);
        pole9.setIcon(null);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
        p1='n';
        p2='n';
        p3='n';
        p4='n';
        p5='n';
        p6='n';
        p7='n';
        p8='n';
        p9='n';
        kto='o';
        pole1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setSelected(true);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
    }
   
 private void sprawdz(){
     if ((p1== p2 && p2==p3 && p1!='n') ||
         (p4== p5 && p5==p6 && p4!='n') ||
         (p7== p8 && p8==p9 && p7!='n') ||
         (p1== p4 && p4==p7 && p1!='n') ||
         (p2== p5 && p5==p8 && p2!='n') ||
         (p3== p6 && p6==p9 && p3!='n') ||
         (p1== p5 && p5==p9 && p9!='n') ||
         (p3== p5 && p5==p7 && p7!='n'))   {
         if (kto=='x') {
            
          
          JOptionPane.showMessageDialog(null, "Wygrywa Kółko!", "Koniec Gry", JOptionPane.INFORMATION_MESSAGE);
          Resetuj();
         }
         else {
          JOptionPane.showMessageDialog(null, "Wygrywa Krzyżyk!", "Koniec Gry", JOptionPane.INFORMATION_MESSAGE);
          Resetuj();
         }
     }
    if (p1=='n' && p2=='n' && p3=='n' && p4=='n' && p5=='n' && p6=='n' && p7=='n' && p8=='n' && p9=='n') {
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
    }
    else {
     jRadioButton1.setEnabled(false);
     jRadioButton2.setEnabled(false);
    }
 }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pole1 = new javax.swing.JLabel();
        pole3 = new javax.swing.JLabel();
        pole2 = new javax.swing.JLabel();
        pole6 = new javax.swing.JLabel();
        pole5 = new javax.swing.JLabel();
        pole4 = new javax.swing.JLabel();
        pole9 = new javax.swing.JLabel();
        pole8 = new javax.swing.JLabel();
        pole7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kółko i Krzyżyk");
        setAlwaysOnTop(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 588, 312));
        setMaximumSize(new java.awt.Dimension(588, 312));
        setMinimumSize(new java.awt.Dimension(588, 312));
        setResizable(false);

        pole1.setBackground(new java.awt.Color(255, 255, 255));
        pole1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole1.setName(""); // NOI18N
        pole1.setOpaque(true);
        pole1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole1MousePressed(evt);
            }
        });

        pole3.setBackground(new java.awt.Color(255, 255, 255));
        pole3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole3.setName(""); // NOI18N
        pole3.setOpaque(true);
        pole3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole3MousePressed(evt);
            }
        });

        pole2.setBackground(new java.awt.Color(255, 255, 255));
        pole2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole2.setName(""); // NOI18N
        pole2.setOpaque(true);
        pole2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole2MousePressed(evt);
            }
        });

        pole6.setBackground(new java.awt.Color(255, 255, 255));
        pole6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole6.setName(""); // NOI18N
        pole6.setOpaque(true);
        pole6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole6MousePressed(evt);
            }
        });

        pole5.setBackground(new java.awt.Color(255, 255, 255));
        pole5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole5.setName(""); // NOI18N
        pole5.setOpaque(true);
        pole5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole5MousePressed(evt);
            }
        });

        pole4.setBackground(new java.awt.Color(255, 255, 255));
        pole4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole4.setName(""); // NOI18N
        pole4.setOpaque(true);
        pole4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole4MousePressed(evt);
            }
        });

        pole9.setBackground(new java.awt.Color(255, 255, 255));
        pole9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole9.setName(""); // NOI18N
        pole9.setOpaque(true);
        pole9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole9MousePressed(evt);
            }
        });

        pole8.setBackground(new java.awt.Color(255, 255, 255));
        pole8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole8.setName(""); // NOI18N
        pole8.setOpaque(true);
        pole8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole8MousePressed(evt);
            }
        });

        pole7.setBackground(new java.awt.Color(255, 255, 255));
        pole7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pole7.setName(""); // NOI18N
        pole7.setOpaque(true);
        pole7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pole7MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Tura gracza");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Zaczyna Kółko");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Zaczyna Krzyżyk");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pole4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pole5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pole6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pole1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pole2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pole3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pole7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pole8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pole9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pole1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pole3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pole2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pole4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pole6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pole5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pole7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pole9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pole8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Resetuj();
    // TODO add your handling code here:;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pole2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole2MousePressed
 if (p2=='n'){
            if (kto=='o') {
                kto='x';
                p2='o';
                pole2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p2='x';
                pole2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole2.setCursor(null);
        }
 sprawdz();
    }//GEN-LAST:event_pole2MousePressed

    private void pole1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole1MousePressed
        if (p1=='n'){
            if (kto=='o') {
                kto='x';
                p1='o';
                pole1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p1='x';
                pole1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole1.setCursor(null);
        }
        
       sprawdz(); 
    }//GEN-LAST:event_pole1MousePressed

    private void pole3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole3MousePressed
 if (p3=='n'){
            if (kto=='o') {
                kto='x';
                p3='o';
                pole3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p3='x';
                pole3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole3.setCursor(null);
        }        // TODO 
    sprawdz();
    }//GEN-LAST:event_pole3MousePressed

    private void pole4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole4MousePressed
 if (p4=='n'){
            if (kto=='o') {
                kto='x';
                p4='o';
                pole4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p4='x';
                pole4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole4.setCursor(null);
        } 
    sprawdz();
    }//GEN-LAST:event_pole4MousePressed

    private void pole5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole5MousePressed
 if (p5=='n'){
            if (kto=='o') {
                kto='x';
                p5='o';
                pole5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p5='x';
                pole5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole5.setCursor(null);
        }    
        sprawdz();
    }//GEN-LAST:event_pole5MousePressed

    private void pole6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole6MousePressed
 if (p6=='n'){
            if (kto=='o') {
                kto='x';
                p6='o';
                pole6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p6='x';
                pole6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole6.setCursor(null);
        }       
        sprawdz();
    }//GEN-LAST:event_pole6MousePressed

    private void pole7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole7MousePressed
 if (p7=='n'){
            if (kto=='o') {
                kto='x';
                p7='o';
                pole7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p7='x';
                pole7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole7.setCursor(null);
        }        
        sprawdz();
    }//GEN-LAST:event_pole7MousePressed

    private void pole8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole8MousePressed
 if (p8=='n'){
            if (kto=='o') {
                kto='x';
                p8='o';
                pole8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p8='x';
                pole8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole8.setCursor(null);
        }       
        sprawdz();
    }//GEN-LAST:event_pole8MousePressed

    private void pole9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pole9MousePressed
        if (p9=='n'){
            if (kto=='o') {
                kto='x';
                p9='o';
                pole9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko1.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
            }
            else {
                kto='o';
                p9='x';
                pole9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko3.png"))); 
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
            }
            pole9.setCursor(null);
        }      
        sprawdz();
    }//GEN-LAST:event_pole9MousePressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        kto='o';
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko2.png"))); 
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        kto='x';
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolko4.png"))); 
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tictactoe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel pole1;
    private javax.swing.JLabel pole2;
    private javax.swing.JLabel pole3;
    private javax.swing.JLabel pole4;
    private javax.swing.JLabel pole5;
    private javax.swing.JLabel pole6;
    private javax.swing.JLabel pole7;
    private javax.swing.JLabel pole8;
    private javax.swing.JLabel pole9;
    // End of variables declaration//GEN-END:variables
}
